title: Card Games
description: collection of card games
name: Jan Weidenhaupt
url: https://jamowei.github.io/
repository: jamowei/card-games
show_downloads: false
plugins:
  - jekyll-include-cache
remote_theme: mmistakes/minimal-mistakes@4.26.2
minimal_mistakes_skin: default # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
locale: en-US
include:
  - _pages
atom_feed:
  hide: true
collections:
  games:
    output: true
    permalink: /:collection/:path/
defaults:
  # _games
  - scope:
      path: ""
      type: games
    values:
      layout: single
      author_profile: false
      share: false
      comments: false